// Comprehensive font list - 200+ Google Fonts + System Fonts (Canva-style)
export const AVAILABLE_FONTS = [
  // System & Web Safe
  { name: "Arial", category: "sans-serif", type: "system" },
  { name: "Verdana", category: "sans-serif", type: "system" },
  { name: "Helvetica", category: "sans-serif", type: "system" },
  { name: "Times New Roman", category: "serif", type: "system" },
  { name: "Georgia", category: "serif", type: "system" },
  { name: "Courier New", category: "monospace", type: "system" },
  { name: "Trebuchet MS", category: "sans-serif", type: "system" },
  { name: "Comic Sans MS", category: "cursive", type: "system" },

  // Top Google Fonts - Sans Serif (Most Popular)
  { name: "Inter", category: "sans-serif", type: "google" },
  { name: "Poppins", category: "sans-serif", type: "google" },
  { name: "Roboto", category: "sans-serif", type: "google" },
  { name: "Open Sans", category: "sans-serif", type: "google" },
  { name: "Lato", category: "sans-serif", type: "google" },
  { name: "Montserrat", category: "sans-serif", type: "google" },
  { name: "Ubuntu", category: "sans-serif", type: "google" },
  { name: "Raleway", category: "sans-serif", type: "google" },
  { name: "Oswald", category: "sans-serif", type: "google" },
  { name: "Source Sans Pro", category: "sans-serif", type: "google" },
  { name: "Work Sans", category: "sans-serif", type: "google" },
  { name: "DM Sans", category: "sans-serif", type: "google" },
  { name: "Quicksand", category: "sans-serif", type: "google" },
  { name: "Nunito", category: "sans-serif", type: "google" },
  { name: "Mulish", category: "sans-serif", type: "google" },
  { name: "Rubik", category: "sans-serif", type: "google" },
  { name: "Sora", category: "sans-serif", type: "google" },
  { name: "Manrope", category: "sans-serif", type: "google" },
  { name: "Barlow", category: "sans-serif", type: "google" },
  { name: "Libre Franklin", category: "sans-serif", type: "google" },
  { name: "Exo", category: "sans-serif", type: "google" },
  { name: "Red Hat Display", category: "sans-serif", type: "google" },
  { name: "Outfit", category: "sans-serif", type: "google" },
  { name: "Space Grotesk", category: "sans-serif", type: "google" },
  { name: "Urbanist", category: "sans-serif", type: "google" },
  { name: "Fredoka", category: "sans-serif", type: "google" },
  { name: "Josefin Sans", category: "sans-serif", type: "google" },
  { name: "Karla", category: "sans-serif", type: "google" },
  { name: "Archivo", category: "sans-serif", type: "google" },
  { name: "Epilogue", category: "sans-serif", type: "google" },
  { name: "Plus Jakarta Sans", category: "sans-serif", type: "google" },
  { name: "Lexend", category: "sans-serif", type: "google" },
  { name: "Albert Sans", category: "sans-serif", type: "google" },
  { name: "Figtree", category: "sans-serif", type: "google" },
  { name: "Comfortaa", category: "sans-serif", type: "google" },
  { name: "Hind", category: "sans-serif", type: "google" },
  { name: "Kanit", category: "sans-serif", type: "google" },
  { name: "Cabin", category: "sans-serif", type: "google" },
  { name: "Noto Sans", category: "sans-serif", type: "google" },
  { name: "PT Sans", category: "sans-serif", type: "google" },
  { name: "Titillium Web", category: "sans-serif", type: "google" },
  { name: "Varela Round", category: "sans-serif", type: "google" },
  { name: "Dosis", category: "sans-serif", type: "google" },
  { name: "Oxygen", category: "sans-serif", type: "google" },
  { name: "Arimo", category: "sans-serif", type: "google" },
  { name: "Assistant", category: "sans-serif", type: "google" },
  { name: "Catamaran", category: "sans-serif", type: "google" },
  { name: "Heebo", category: "sans-serif", type: "google" },
  { name: "Maven Pro", category: "sans-serif", type: "google" },
  { name: "Signika", category: "sans-serif", type: "google" },
  { name: "Overpass", category: "sans-serif", type: "google" },
  { name: "Jost", category: "sans-serif", type: "google" },
  { name: "Anton", category: "sans-serif", type: "google" },
  { name: "Acme", category: "sans-serif", type: "google" },
  { name: "Prompt", category: "sans-serif", type: "google" },
  { name: "Questrial", category: "sans-serif", type: "google" },
  { name: "Saira", category: "sans-serif", type: "google" },

  // Google Fonts - Serif
  { name: "Playfair Display", category: "serif", type: "google" },
  { name: "Lora", category: "serif", type: "google" },
  { name: "Crimson Text", category: "serif", type: "google" },
  { name: "Merriweather", category: "serif", type: "google" },
  { name: "Bitter", category: "serif", type: "google" },
  { name: "Libre Baskerville", category: "serif", type: "google" },
  { name: "Cormorant Garamond", category: "serif", type: "google" },
  { name: "EB Garamond", category: "serif", type: "google" },
  { name: "Prata", category: "serif", type: "google" },
  { name: "Cinzel", category: "serif", type: "google" },
  { name: "Bodoni Moda", category: "serif", type: "google" },
  { name: "Spectral", category: "serif", type: "google" },
  { name: "Cardo", category: "serif", type: "google" },
  { name: "Vollkorn", category: "serif", type: "google" },
  { name: "Literata", category: "serif", type: "google" },
  { name: "Noto Serif", category: "serif", type: "google" },
  { name: "PT Serif", category: "serif", type: "google" },
  { name: "Slabo 27px", category: "serif", type: "google" },
  { name: "Arvo", category: "serif", type: "google" },
  { name: "Rokkitt", category: "serif", type: "google" },
  { name: "Old Standard TT", category: "serif", type: "google" },
  { name: "Alegreya", category: "serif", type: "google" },
  { name: "Neuton", category: "serif", type: "google" },
  { name: "Domine", category: "serif", type: "google" },
  { name: "Crete Round", category: "serif", type: "google" },
  { name: "Gilda Display", category: "serif", type: "google" },
  { name: "Yeseva One", category: "serif", type: "google" },
  { name: "Bree Serif", category: "serif", type: "google" },
  { name: "Trocchi", category: "serif", type: "google" },
  { name: "Cantata One", category: "serif", type: "google" },

  // Google Fonts - Display & Decorative
  { name: "Bebas Neue", category: "display", type: "google" },
  { name: "Abril Fatface", category: "display", type: "google" },
  { name: "Lobster", category: "display", type: "google" },
  { name: "Pacifico", category: "display", type: "google" },
  { name: "Righteous", category: "display", type: "google" },
  { name: "Fredoka One", category: "display", type: "google" },
  { name: "Bangers", category: "display", type: "google" },
  { name: "Permanent Marker", category: "display", type: "google" },
  { name: "Alfa Slab One", category: "display", type: "google" },
  { name: "Bungee", category: "display", type: "google" },
  { name: "Monoton", category: "display", type: "google" },
  { name: "Staatliches", category: "display", type: "google" },
  { name: "Teko", category: "display", type: "google" },
  { name: "Archivo Black", category: "display", type: "google" },
  { name: "Passion One", category: "display", type: "google" },
  { name: "Squada One", category: "display", type: "google" },
  { name: "Patua One", category: "display", type: "google" },
  { name: "Ultra", category: "display", type: "google" },
  { name: "Russo One", category: "display", type: "google" },
  { name: "Yellowtail", category: "display", type: "google" },
  { name: "Fjalla One", category: "display", type: "google" },
  { name: "Titan One", category: "display", type: "google" },
  { name: "Black Ops One", category: "display", type: "google" },
  { name: "Lilita One", category: "display", type: "google" },
  { name: "Kalam", category: "display", type: "google" },
  { name: "Cookie", category: "display", type: "google" },
  { name: "Shadows Into Light", category: "display", type: "google" },
  { name: "Indie Flower", category: "display", type: "google" },
  { name: "Amatic SC", category: "display", type: "google" },
  { name: "Satisfy", category: "display", type: "google" },
  { name: "Courgette", category: "display", type: "google" },
  { name: "Sacramento", category: "display", type: "google" },
  { name: "Gruppo", category: "display", type: "google" },
  { name: "Rampart One", category: "display", type: "google" },
  { name: "Creepster", category: "display", type: "google" },
  { name: "Eater", category: "display", type: "google" },
  { name: "Fascinate", category: "display", type: "google" },

  // Google Fonts - Handwriting & Script
  { name: "Caveat", category: "handwriting", type: "google" },
  { name: "Dancing Script", category: "handwriting", type: "google" },
  { name: "Great Vibes", category: "handwriting", type: "google" },
  { name: "Kaushan Script", category: "handwriting", type: "google" },
  { name: "Alex Brush", category: "handwriting", type: "google" },
  { name: "Allura", category: "handwriting", type: "google" },
  { name: "Parisienne", category: "handwriting", type: "google" },
  { name: "Pinyon Script", category: "handwriting", type: "google" },
  { name: "Tangerine", category: "handwriting", type: "google" },
  { name: "Monsieur La Doulaise", category: "handwriting", type: "google" },
  { name: "Mr Dafoe", category: "handwriting", type: "google" },
  { name: "Homemade Apple", category: "handwriting", type: "google" },
  { name: "Pathway Gothic One", category: "handwriting", type: "google" },
  { name: "Patrick Hand", category: "handwriting", type: "google" },
  { name: "Architects Daughter", category: "handwriting", type: "google" },
  { name: "Reenie Beanie", category: "handwriting", type: "google" },
  { name: "Cedarville Cursive", category: "handwriting", type: "google" },
  { name: "Bad Script", category: "handwriting", type: "google" },
  { name: "Gloria Hallelujah", category: "handwriting", type: "google" },

  // Google Fonts - Monospace
  { name: "Roboto Mono", category: "monospace", type: "google" },
  { name: "IBM Plex Mono", category: "monospace", type: "google" },
  { name: "JetBrains Mono", category: "monospace", type: "google" },
  { name: "Inconsolata", category: "monospace", type: "google" },
  { name: "Source Code Pro", category: "monospace", type: "google" },
  { name: "Courier Prime", category: "monospace", type: "google" },
  { name: "Fira Code", category: "monospace", type: "google" },
  { name: "Space Mono", category: "monospace", type: "google" },
  { name: "Ubuntu Mono", category: "monospace", type: "google" },
  { name: "Anonymous Pro", category: "monospace", type: "google" },
  { name: "Share Tech Mono", category: "monospace", type: "google" },
  { name: "Overpass Mono", category: "monospace", type: "google" },
  { name: "PT Mono", category: "monospace", type: "google" },
  { name: "Cutive Mono", category: "monospace", type: "google" },
  { name: "VT323", category: "monospace", type: "google" },
  { name: "Major Mono Display", category: "monospace", type: "google" },
  { name: "Red Hat Mono", category: "monospace", type: "google" },
  { name: "Nanum Gothic Coding", category: "monospace", type: "google" },
];

export function searchFonts(query: string): typeof AVAILABLE_FONTS {
  if (!query.trim()) return AVAILABLE_FONTS;

  const lowerQuery = query.toLowerCase();
  return AVAILABLE_FONTS.filter((font) =>
    font.name.toLowerCase().includes(lowerQuery) ||
    font.category.toLowerCase().includes(lowerQuery)
  );
}
