import { Template } from "./storage";

export const defaultTemplates: Template[] = [
  {
    id: "template-product-promo",
    name: "Product Promo",
    description: "Professional product promotion video with text overlay",
    createdAt: new Date().toISOString(),
    tags: ["product", "promo", "business"],
    project: {
      id: "template-product-promo",
      name: "Product Promo",
      width: 1920,
      height: 1080,
      fps: 30,
      durationInFrames: 150,
      layers: [
        {
          id: "bg-1",
          type: "background",
          name: "Background",
          from: 0,
          to: 150,
          zIndex: 0,
          enabled: true,
          src: "https://images.unsplash.com/photo-1557821552-17105176677c?w=1920&h=1080&fit=crop",
          fit: "cover",
          transitionIn: { type: "fade", duration: 15 },
          transitionOut: { type: "fade", duration: 15 },
        },
        {
          id: "text-1",
          type: "text",
          name: "Title",
          from: 15,
          to: 135,
          zIndex: 10,
          enabled: true,
          text: "Your Product Name",
          x: 100,
          y: 400,
          fontSize: 120,
          lineHeight: 1.2,
          letterSpacing: 0,
          color: "#ffffff",
          opacity: 1,
          fontFamily: "Inter",
          fontWeight: 700,
          fontStyle: "normal",
          textTransform: "none",
          align: "left",
          shadow: { enabled: true, color: "rgba(0,0,0,0.8)", x: 0, y: 8, blur: 24 },
          stroke: { enabled: false, color: "#000000", width: 6 },
          background: {
            enabled: false,
            color: "rgba(0,0,0,0.35)",
            paddingX: 18,
            paddingY: 10,
            radius: 14,
          },
          animationIn: { type: "slideUp", duration: 20, distance: 100 },
          animationOut: { type: "fade", duration: 15 },
          transitionIn: { type: "slideUp", duration: 20, distance: 100 },
          transitionOut: { type: "fade", duration: 15 },
        },
        {
          id: "text-2",
          type: "text",
          name: "Subtitle",
          from: 30,
          to: 135,
          zIndex: 11,
          enabled: true,
          text: "Change this text to describe your product",
          x: 100,
          y: 560,
          fontSize: 48,
          lineHeight: 1.3,
          letterSpacing: 0,
          color: "#e0e0e0",
          opacity: 1,
          fontFamily: "Inter",
          fontWeight: 400,
          fontStyle: "normal",
          textTransform: "none",
          align: "left",
          shadow: { enabled: true, color: "rgba(0,0,0,0.6)", x: 0, y: 4, blur: 12 },
          stroke: { enabled: false, color: "#000000", width: 6 },
          background: {
            enabled: false,
            color: "rgba(0,0,0,0.35)",
            paddingX: 18,
            paddingY: 10,
            radius: 14,
          },
          animationIn: { type: "fade", duration: 20 },
          animationOut: { type: "fade", duration: 15 },
          transitionIn: { type: "fade", duration: 20 },
          transitionOut: { type: "fade", duration: 15 },
        },
      ],
    },
  },
  {
    id: "template-social-quote",
    name: "Social Media Quote",
    description: "Eye-catching quote card for social media",
    createdAt: new Date().toISOString(),
    tags: ["social", "quote", "instagram"],
    project: {
      id: "template-social-quote",
      name: "Social Media Quote",
      width: 1080,
      height: 1080,
      fps: 30,
      durationInFrames: 180,
      layers: [
        {
          id: "bg-1",
          type: "background",
          name: "Background",
          from: 0,
          to: 180,
          zIndex: 0,
          enabled: true,
          src: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1080&h=1080&fit=crop",
          fit: "cover",
          transitionIn: { type: "zoom", duration: 20, from: 1.2 },
          transitionOut: { type: "zoom", duration: 20, from: 0.9 },
        },
        {
          id: "text-1",
          type: "text",
          name: "Quote",
          from: 20,
          to: 160,
          zIndex: 10,
          enabled: true,
          text: '"Edit this inspiring quote"',
          x: 100,
          y: 400,
          fontSize: 72,
          lineHeight: 1.4,
          letterSpacing: 1,
          color: "#ffffff",
          opacity: 1,
          fontFamily: "Inter",
          fontWeight: 600,
          fontStyle: "normal",
          textTransform: "none",
          align: "center",
          shadow: { enabled: true, color: "rgba(0,0,0,0.9)", x: 0, y: 6, blur: 20 },
          stroke: { enabled: false, color: "#000000", width: 6 },
          background: {
            enabled: true,
            color: "rgba(0,0,0,0.5)",
            paddingX: 40,
            paddingY: 30,
            radius: 20,
          },
          animationIn: { type: "scaleIn", duration: 25, from: 0.8 },
          animationOut: { type: "fade", duration: 20 },
          transitionIn: { type: "zoom", duration: 25, from: 0.8 },
          transitionOut: { type: "fade", duration: 20 },
        },
      ],
    },
  },
  {
    id: "template-announcement",
    name: "Announcement",
    description: "Bold announcement video with multiple text layers",
    createdAt: new Date().toISOString(),
    tags: ["announcement", "news", "update"],
    project: {
      id: "template-announcement",
      name: "Announcement",
      width: 1280,
      height: 720,
      fps: 30,
      durationInFrames: 120,
      layers: [
        {
          id: "bg-1",
          type: "background",
          name: "Background",
          from: 0,
          to: 120,
          zIndex: 0,
          enabled: true,
          src: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=1280&h=720&fit=crop",
          fit: "cover",
          transitionIn: { type: "fade", duration: 12 },
          transitionOut: { type: "fade", duration: 12 },
        },
        {
          id: "text-1",
          type: "text",
          name: "Announcement",
          from: 10,
          to: 110,
          zIndex: 10,
          enabled: true,
          text: "BIG NEWS!",
          x: 640,
          y: 280,
          fontSize: 140,
          lineHeight: 1.1,
          letterSpacing: 4,
          color: "#ffdd00",
          opacity: 1,
          fontFamily: "Inter",
          fontWeight: 900,
          fontStyle: "normal",
          textTransform: "uppercase",
          align: "center",
          shadow: { enabled: true, color: "rgba(0,0,0,1)", x: 0, y: 10, blur: 30 },
          stroke: { enabled: true, color: "#000000", width: 8 },
          background: {
            enabled: false,
            color: "rgba(0,0,0,0.35)",
            paddingX: 18,
            paddingY: 10,
            radius: 14,
          },
          animationIn: { type: "scaleIn", duration: 20, from: 0.5 },
          animationOut: { type: "fade", duration: 12 },
          transitionIn: { type: "zoom", duration: 20, from: 0.5 },
          transitionOut: { type: "fade", duration: 12 },
        },
        {
          id: "text-2",
          type: "text",
          name: "Details",
          from: 30,
          to: 110,
          zIndex: 11,
          enabled: true,
          text: "Edit this text with your announcement details",
          x: 640,
          y: 450,
          fontSize: 40,
          lineHeight: 1.3,
          letterSpacing: 0,
          color: "#ffffff",
          opacity: 1,
          fontFamily: "Inter",
          fontWeight: 500,
          fontStyle: "normal",
          textTransform: "none",
          align: "center",
          shadow: { enabled: true, color: "rgba(0,0,0,0.8)", x: 0, y: 4, blur: 16 },
          stroke: { enabled: false, color: "#000000", width: 6 },
          background: {
            enabled: false,
            color: "rgba(0,0,0,0.35)",
            paddingX: 18,
            paddingY: 10,
            radius: 14,
          },
          animationIn: { type: "slideUp", duration: 18, distance: 80 },
          animationOut: { type: "fade", duration: 12 },
          transitionIn: { type: "slideUp", duration: 18, distance: 80 },
          transitionOut: { type: "fade", duration: 12 },
        },
      ],
    },
  },
];
